[build]
  publish = "dist"
  command = "npm run build"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[plugins]]
package = '@netlify/plugin-sitemap'

[plugins.inputs]
buildDir = "dist" # Change this to match your build output folder (e.g., "public", "build", or ".")